services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mileapp-tasks-client-dev
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL}
      - NUXT_PRIVATE_API_BASE_URL=${NUXT_PRIVATE_API_BASE_URL}
    command: npm run dev
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mileapp-tasks-server-dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGODB_PORT}/${MONGODB_NAME}?authSource=admin
      - PORT=${SERVER_PORT}
    command: npx nodemon server.js
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: mileapp-tasks-mongo-dev
    restart: always
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data-dev:/data/db

volumes:
  mongo-data-dev:
